---
kubernetes:
  children:
    master:
      hosts:
        k3s-node-2:
          ansible_host: 192.168.1.214
        k3s-node-4:
          ansible_host: 192.168.1.48
        k3s-node-6:
          ansible_host: 192.168.1.213
    worker:
      hosts:
