apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:t0m3AKmALPtFiYfeeQoD/3/4aZoWU7RJUkHZvzyU8n4BSq+4u0VZmBOPaO8RJ80PjTyVxqHXwabjyix2HCX+28VcBu0eAV4fKb1sSJir4TidQ95zWCX9hIIBX8QxZ8UluLz6shsq+patHF7IFCcrlA8bLy2Gm75BZnACv7/tK5932TXExsyyG0FDK+Mv5XoklF84ktsH/epOtHwpSHvoD1XbugAUReDwRw+YAzL9vWvPH4gmuqgMhlaSzLX6SGM/KDc4bRqfCA8t6S+bZFyBWN1F1RUaekhbt4bDvJ9FSLAjCnBEMLgpA/v/P64=,iv:Diiq+Mp9lxAET1ONKi3W5QnQp2FNCQBz5WAuFPVeim8=,tag:aJMEnChwXa0zLf8zwg9XpA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: ghcr-credentials
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p5stz83fpyrey8h89n7fs0p2us9pgv7gdtjt7legsgckyqfh5fdszqlnah
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWGJ6cjJ3QnpvQkNqK2dU
            SGpJM2Y1UVRWTXFDK1kwQmJMeDVzWXpsQkU4Cjk2RDVtMVZMS2FKNGNtTlRyazdx
            cnZubWY3emJWZWZ6OC9xR20yaTJVa1UKLS0tIFRFeXBVMHo3OE8vQm5MOW9ranln
            RmNIdk0ySEI4bHVOdW14azFHeHRHTGcKRfEfRx/ebC90D5Or6AJShnpsc7IH8S6Q
            ngf2fzz18LhaT8er4S5H/oSS/O6jh7ZjzRLTJMBjQwH74ANomF6tjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T21:35:56Z"
    mac: ENC[AES256_GCM,data:WrGDzD3EdtydDIv+DIO/mNpcWb4SkcgHy89Q8s3ZAUGylVFOz3rEYzTm5BRNjaNl1ki/DxNwBK+jmZ5JIuOjGzBUh1powpdpKhcXfFK4HUpkMG3AyRZyFT/+aKrKi3kVDptVns1p4+jcif4x8BCgbnUNTltxpWid9dBY8O9ikRo=,iv:Hz5SEfmg8YIKcrRb6+RpIIV7ouFDi5tI2SUdvZ4PQeY=,tag:7Rx2gsHhU4gLcae7+nefKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
