apiVersion: v1
kind: Secret
metadata:
    name: home-kubernetes-write-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:wTSpnv0sv+Y=,iv:aMGDxT7p/xm2CiozTsCyFz3dFgQqcSFA6+tE2MAIQQw=,tag:se1u8jX9TO/9lkQqmfusUA==,type:str]
    password: ENC[AES256_GCM,data:9OC35MxmbBXWB7tpCyF2RLFtuQdvCa8qQPQclWFB6D7lCpJKW/xnVg==,iv:RlkvJBioxcBPsNLaarpJvCTNktOPwgVANYh02IWBNEU=,tag:F/kHH2rGPW823QmJ4Bzu4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p5stz83fpyrey8h89n7fs0p2us9pgv7gdtjt7legsgckyqfh5fdszqlnah
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3L09tRjdnaXR1TjBpNHV2
            M2ExbEJrK2ovcll2bWNVUVdEUnA0SlhCZ21RCjlLUkRKeXIzb2FSVDFqdHJlODND
            alBWUFlvc3BxeWN1ZGdvdjZnY3dHQ0UKLS0tIDhIOXl2SW5KaXY3VEhncGJVZ0VH
            dGkvcjJMcGQ1TElMYkFBdm1JS1NQTVUKIMBfjfOQW9jKdrQhECX/jYQgnLi4erIF
            Wtzt4ixyWHyV17LtvZEBKH4rn9rwZGsHWhMOC3Th1cO1I46UM7e6rQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T21:43:47Z"
    mac: ENC[AES256_GCM,data:AJexOsJ/JTWWKNN/zRnGSHQ+Zdv6tbpYTFalx5Dl2hAN6hLzHV27Hn64TqD67hsB73o+r/oC0/vtjd5f2OQLfLZLKIQLc4+7EWi9Rtb41xcZR/RTdlf17mw1QGgzqrJ0KYVIC73dtpGPjiiTWIoCjyvdqjOqWRjDuk9fqikigCs=,iv:Wkxf2YklY6R6a5GM7pE6/o2et3t9j1YI2TGABIyC3hs=,tag:mCkZeq17ctwHIuDRk888CQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
