---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gitrepository-write.yaml
  - github-write-auth.secret.sops.yaml
  - ghcr-read.secret.sops.yaml
  - tbd-imagerepo.yaml
  - tbd-imagepolicy.yaml
  - tbd-imageupdateautomation.yaml
