---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: tbd
  namespace: flux-system
spec:
  image: ghcr.io/hwestman/tbd
  interval: 1m
  secretRef:
    name: ghcr-credentials
