---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-tbd
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-ghcr-credentials
  path: ./kubernetes/apps/default/tbd
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: tbd
      namespace: default
  interval: 30m
  retryInterval: 1m
  timeout: 3m
