apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:AM1bftvguyZHd2RLjfa2B2YMq/nUj6BIrOAofNDyI11XcE8JahoHrMah8kK19DqKyrTkgZmj2/i2nUc5l5BLRqUSOyjx8IqdpfupBXp/37DhussUbZruNVS7RLHE4Ab8oxMPhs48Hy1gk/PYd3T2KXy7Y+sHqO1mmULjXI13OTDfP+cEUn9dluDjRmWuDfcgJ97JN6HN3n/PbGfPk34TAIxsWM/SzPaLnnK3VXxf/qSuv3rJiosa+/yOevvG6J6x00a2lXQOs/vYRjg/KzNyCRHxyuFMntp7b1VPFsIHdgBECYiN+wQuLTV6RRg=,iv:MaenCJBnEcR+T8uKYTNqkWMTQOB/FB+I1zFEPLqkpSU=,tag:2llLlDQrJpHIm7k+IpBFFw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: ghcr-credentials
    namespace: default
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p5stz83fpyrey8h89n7fs0p2us9pgv7gdtjt7legsgckyqfh5fdszqlnah
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZVRmWjBGYUx1MkZmYlRS
            LzlzVUVTVGpQaU5wZytzcVduMFI3U21qUG5ZClppUW0xWTZDTVpNRkRFOFA2dGdX
            VVFGalVXZUlZblVqZktkcEhqZnRpemsKLS0tIGJ6VGFsTVl2V3pVNzhYTTZERFN1
            elgvUEJuRnpBTlB4L004bDBuT1Jkc2sKnnwmgZHc0O++SwJ+oJGPHqqEzZjZK6md
            mLaNFq43hxRNzlZiZioTRYtcAvjvMG7d1maOHZGmwS+7/Fh8tQd8WA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T20:58:24Z"
    mac: ENC[AES256_GCM,data:xkW8eVLpsFadn0OUmTj7HZNwOw2lIVi9yoNK7UnFrzgjSzjoyGF7RLTZfkaI+iS+9TwH/Wc5oO6O3GXt2DSMnEt09zWaaiuDkVYL4MlJws3yi1cgUElzl6x0SjW9yxKIgsDp0K7vLAEQvWw21USe7Z2M4HEVQf1sUYs8xOuADLc=,iv:s60kifxHAlc2pEh2ypL0dt5yP9nQncHeK4iUfcQrDP4=,tag:l6gq5FwjTrO9jJm2UM2wng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
